// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=repository_mock.go -package=org
//

// Package org is a generated GoMock package.
package org

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m_2 *MockRepository) AddMember(ctx context.Context, m *Membership) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "AddMember", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMember indicates an expected call of AddMember.
func (mr *MockRepositoryMockRecorder) AddMember(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockRepository)(nil).AddMember), ctx, m)
}

// CreateWithOwner mocks base method.
func (m *MockRepository) CreateWithOwner(ctx context.Context, o *Organization, ownerID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithOwner", ctx, o, ownerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithOwner indicates an expected call of CreateWithOwner.
func (mr *MockRepositoryMockRecorder) CreateWithOwner(ctx, o, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithOwner", reflect.TypeOf((*MockRepository)(nil).CreateWithOwner), ctx, o, ownerID)
}

// GetMembership mocks base method.
func (m *MockRepository) GetMembership(ctx context.Context, userID, orgID uuid.UUID) (*Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembership", ctx, userID, orgID)
	ret0, _ := ret[0].(*Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembership indicates an expected call of GetMembership.
func (mr *MockRepositoryMockRecorder) GetMembership(ctx, userID, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembership", reflect.TypeOf((*MockRepository)(nil).GetMembership), ctx, userID, orgID)
}

// ListForUser mocks base method.
func (m *MockRepository) ListForUser(ctx context.Context, userID uuid.UUID) ([]*Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForUser", ctx, userID)
	ret0, _ := ret[0].([]*Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForUser indicates an expected call of ListForUser.
func (mr *MockRepositoryMockRecorder) ListForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForUser", reflect.TypeOf((*MockRepository)(nil).ListForUser), ctx, userID)
}

// RevokeMember mocks base method.
func (m *MockRepository) RevokeMember(ctx context.Context, orgID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeMember", ctx, orgID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeMember indicates an expected call of RevokeMember.
func (mr *MockRepositoryMockRecorder) RevokeMember(ctx, orgID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeMember", reflect.TypeOf((*MockRepository)(nil).RevokeMember), ctx, orgID, userID)
}
